name: parse_dashboard
description: A Flutter application for managing Parse Dashboard instance.
publish_to: none
version: 1.0.1+2

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_parse:
   git:
     url: https://github.com/eyro-labs/flutter_parse
     ref: master
  flutter_parse_storage_shared_preferences: ^1.0.1
  device_info: ^2.0.3
  package_info: ^2.0.2
#  sentry: ^3.0.0+1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  meta: ^1.7.0

flutter:
  uses-material-design: true
  assets:
   - assets/json/parse-credentials.json
