name: Analyze, Test And Build

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  analyze:
    name: Analyze on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1.1.1
        with:
          flutter-version: '1.11.0'
          channel: 'beta'
      - name: "Rename json file example"
        run: mv assets/json/parse-credentials-sample.json assets/json/parse-credentials.json
      - name: "Running flutter analyzer"
        run: flutter analyze

  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1.1.1
        with:
          flutter-version: '1.11.0'
          channel: 'beta'
      - name: "Rename json file example"
        run: mv assets/json/parse-credentials-sample.json assets/json/parse-credentials.json
      - name: "Running flutter test"
        run: flutter test

  build-android:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1.1.1
        with:
          flutter-version: '1.11.0'
          channel: 'beta'
      - name: "Using predefined parse-credentials.json"
        run: echo "[{"configuration":{"server":"https://parseapi.back4app.com/","applicationId":"DekBV7i5yTYOR5suPzvJJUXO4YBrMDeEVc3cVDAk","masterKey":"nUdWWPUNbYwxD7rVYSvWWzv7uwPhiLSH6wVKbQER","localStoragePath":"/tmp","enableLogging":false},"appName":"Parse-Dashboard-Test","icon":{"codePoint":"0xe420","fontFamily":"MaterialIcons"}}]" > assets/json/parse-credentials.json
      - name: "Install flutter packages"
        run: flutter packages get
      - name: "Build Android APK split per abi"
        run: flutter build apk --release --target-platform android-arm,android-arm64 --split-per-abi -v

  # build-ios:
  #   name: Build on ${{ matrix.os }}
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [macos-latest]
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-java@v1
  #       with:
  #         java-version: '12.x'
  #     - uses: subosito/flutter-action@v1.1.1
  #       with:
  #         flutter-version: '1.11.0'
  #         channel: 'beta'
  #     - name: "Using predefined parse-credentials.json"
  #       run: echo "[{"configuration":{"server":"https://parseapi.back4app.com/","applicationId":"DekBV7i5yTYOR5suPzvJJUXO4YBrMDeEVc3cVDAk","masterKey":"nUdWWPUNbYwxD7rVYSvWWzv7uwPhiLSH6wVKbQER","localStoragePath":"/tmp","enableLogging":false},"appName":"Parse-Dashboard-Test","icon":{"codePoint":"0xe420","fontFamily":"MaterialIcons"}}]" > assets/json/parse-credentials.json
  #     - name: "Install flutter packages"
  #       run: flutter packages get
  #     - name: "Build iOS for archieving preparation"
  #       run: flutter build ios --release -v