name: Coverage

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: "Rename parse-credentials-sample.json > parse-credentials.json"
      run: mv assets/json/parse-credentials-sample.json assets/json/parse-credentials.json
    - name: Generate coverage report
      run: flutter test --coverage --coverage-path ./coverage/lcov.info
    - name: Send to codecov.io
      run: bash <(curl -s https://codecov.io/bash)