name: APK Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    name: to Github Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: subosito/flutter-action@v1.4.0
      with:
        flutter-version: '1.25.0-8.0.pre'
        channel: 'dev'
    - name: "Create parse-credentials.json"
      run: echo '[{"configuration":{"server":"https://parseapi.back4app.com/","applicationId":"DekBV7i5yTYOR5suPzvJJUXO4YBrMDeEVc3cVDAk","masterKey":"nUdWWPUNbYwxD7rVYSvWWzv7uwPhiLSH6wVKbQER","enableLogging":false},"appName":"Parse-Dashboard-Test","icon":{"codePoint":"0xe420","fontFamily":"MaterialIcons"}}]' > assets/json/parse-credentials.json
    - run: flutter analyze
    - run: flutter test
    - run: flutter packages get
    - name: Create a Release APK
      run: flutter build apk --release --target-platform android-arm,android-arm64 --split-per-abi
    - name: Push APK to Releases
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/release/*.apk"
        token: ${{ secrets.TOKEN }}