name: Test

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1.1.1
        with:
          flutter-version: '1.11.0'
          channel: 'beta'
      - name: "Rename parse-credentials-sample.json > parse-credentials.json"
        run: mv assets/json/parse-credentials-sample.json assets/json/parse-credentials.json
      - run: flutter test